# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5368a9103f2b913930366244e2291d43bc626036a8b032ceeffbe787347364f75ba2e902b6b4293d3047c65f88941093d47327c6af4d94bdbb45a8c4281cd993

test:
  secret_key_base: 4818a7478c3ad81a684992d1ccf23a91a5f8cf3ec2ab8df784d79126974c71a32ed1fbc4dec404eca5e6614e16c8748fcef1afe274977ffd59daa4ab7e727602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
